version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: gct-insight-chat-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - gct-apps
  chromadb:
    image: chromadb/chroma:0.6.1
    container_name: gct-insight-chat-chromadb
    restart: always
    ports:
      - "8000:8000"
    networks:
      - gct-apps
    volumes:
      - chromadb_data:/data
  mysql:
    image: mysql:8.0.19
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  postgres:
    image: postgres:latest
    container_name: gct-insight-chat-postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - gct-apps
    volumes:
      - chromadb_data:/data
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gct-insight-chat-nextjs
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    restart: always
    ports:
      - "3000:3000"
    networks:
      - gct-apps
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gct-insight-chat-fastapi
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - gct-apps
    volumes:
      - backend_data:/var/app/backend/uploads

volumes:
  redis_data:
    driver: local
  chromadb_data:
    driver: local
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  backend_data:
    driver: local

networks:
  gct-apps:
