"""Initial migration 2

Revision ID: d31042fdfdbb
Revises: 3e8a12850245
Create Date: 2025-03-12 14:45:59.324783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31042fdfdbb'
down_revision: Union[str, None] = '3e8a12850245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatfile_file_name', table_name='chatfile')
    op.drop_index('ix_chatfile_mime_type', table_name='chatfile')
    op.drop_index('ix_chatfile_path_name', table_name='chatfile')
    op.drop_table('chatfile')
    op.drop_index('ix_chat_created_at', table_name='chat')
    op.drop_index('ix_chat_description', table_name='chat')
    op.drop_index('ix_chat_title', table_name='chat')
    op.drop_index('ix_chat_updated_at', table_name='chat')
    op.drop_index('ix_chat_user_id', table_name='chat')
    op.drop_table('chat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('context', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('avatar_path', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_user_id', 'chat', ['user_id'], unique=False)
    op.create_index('ix_chat_updated_at', 'chat', ['updated_at'], unique=False)
    op.create_index('ix_chat_title', 'chat', ['title'], unique=False)
    op.create_index('ix_chat_description', 'chat', ['description'], unique=False)
    op.create_index('ix_chat_created_at', 'chat', ['created_at'], unique=False)
    op.create_table('chatfile',
    sa.Column('file_name', sa.VARCHAR(), nullable=False),
    sa.Column('path_name', sa.VARCHAR(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatfile_path_name', 'chatfile', ['path_name'], unique=False)
    op.create_index('ix_chatfile_mime_type', 'chatfile', ['mime_type'], unique=False)
    op.create_index('ix_chatfile_file_name', 'chatfile', ['file_name'], unique=False)
    # ### end Alembic commands ###
