"""change chat_id to model

Revision ID: ff5c429a9d90
Revises: cfbc0f056af4
Create Date: 2025-03-12 23:34:56.113023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5c429a9d90'
down_revision: Union[str, None] = 'cfbc0f056af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favourite")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatfile',
    sa.Column('file_name', sa.VARCHAR(), nullable=False),
    sa.Column('path_name', sa.VARCHAR(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), nullable=False),
    sa.Column('chat_id', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('context', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('avatar_path', sa.VARCHAR(), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.Column('last_interacted_at', sa.DATETIME(), nullable=True),
    sa.Column('model', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourite',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
