name: Test Build Docker Images on Dev

on:
  push:
    branches:
      - dev # Only run on pushes to the 'dev' branch
    paths:
      # --- Backend Files ---
      # Python source files
      - 'backend/**/*.py'
      # Common config/dependency files
      - 'backend/requirements*.txt'
      - 'backend/pyproject.toml'
      - 'backend/**.ini'
      - 'backend/**.toml'
      # Dockerfile for backend
      - 'backend/Dockerfile'

      # --- Frontend Files ---
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'
      - 'frontend/**/*.js'
      - 'frontend/**/*.jsx'
      - 'frontend/**/*.css'
      - 'frontend/**/*.scss'
      - 'frontend/**/*.sass'
      - 'frontend/**/*.less'
      - 'frontend/package.json'
      - 'frontend/yarn.lock'
      - 'frontend/package-lock.json'
      - 'frontend/pnpm-lock.yaml'
      - 'frontend/**.json' # Covers tsconfig.json, etc.
      - 'frontend/**.yaml'
      - 'frontend/**.yml'
      - 'frontend/**.html'
      - 'frontend/tailwind.config.*' # .js, .ts, .cjs
      - 'frontend/postcss.config.*'  # .js, .ts, .cjs
      - 'frontend/next.config.*'     # .js, .mjs
      - 'frontend/Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_BASENAME: ${{ github.repository }}
  OLLAMA_MODEL: llama3.2

jobs:
  test-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Extract Git Commit ID
        id: vars
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set OLLAMA_MODEL environment variable
        run: echo "OLLAMA_MODEL=llama3.2" >> $GITHUB_ENV
      
      - uses: actions/cache@v4
        with:
          path: ~/.ollama
          key: ${{ runner.os }}-ollama

      - name: Setup Ollama
        uses: ai-action/setup-ollama@v1

      - name: Pull LLM
        run: ollama pull llama3.2
      
      - name: Pull Embedding Model
        run: ollama pull mxbai-embed-large
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: backend/requirements.dev.txt

      - name: Set up Python virtual environment and install dependencies. Run unit tests.
        run: |
          cd backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.dev.txt
          deepeval test run ./tests/test_llm_app.py 
          cd ..

      - name: Build and tag fastapi Docker image
        run: |
          docker build -t fastapi:${{ env.commit_id }} ./backend
          echo "FastAPI build successful for commit ${{ env.commit_id }}"

      - name: Build and tag nextjs Docker image
        run: |
          docker build -t nextjs:${{ env.commit_id }} ./frontend
          echo "Next.js build successful for commit ${{ env.commit_id }}"