name: Build Docker Images

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git Commit ID
        id: vars
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and tag fastapi Docker image
        run: |
          docker build -t fastapi:${{ env.commit_id }} ./backend
          echo "FastAPI build successful"

      - name: Build and tag nextjs Docker image
        run: |
          docker build -t nextjs:${{ env.commit_id }} ./frontend
          echo "Next.js build successful"
