name: Build and Push FastAPI & Next.js to GHCR

on:
  # Trigger on tags AND when the test workflow succeeds
  workflow_run:
    workflows: ["Test Build Docker Images on Dev"]
    branches: [dev]
    types:
      - completed
  # Also allow manual triggers and tag pushes (but will check test status)
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_BASENAME: ${{ github.repository }}

jobs:
  check-tests-and-build:
    # Only proceed if the test workflow succeeded OR this is a tag push
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # For tag pushes, check out the exact tagged commit
        with:
          ref: ${{ github.ref }}

      - name: Verify tests passed (for non-tag triggers)
        if: github.event_name == 'workflow_run'
        run: |
          echo "Test workflow ${{ github.event.workflow_run.id }} succeeded"
          
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ... rest of your existing build/push steps ...
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata for FastAPI
        id: meta-fastapi
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/fastapi
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=true

      - name: Build and push FastAPI Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta-fastapi.outputs.tags }}
          labels: ${{ steps.meta-fastapi.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract Docker metadata for Next.js
        id: meta-nextjs
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/nextjs
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=true

      - name: Build and push Next.js Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-nextjs.outputs.tags }}
          labels: ${{ steps.meta-nextjs.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max